build : website

website : index page

index : html css js js
html :
	@cd gen/
	@node groq-html.js	
css :
	@cd gen/
	@node groq-html.js
js :
	@cd gen/
	@node groq-js.js
json :
	@cd gen/
	@node groq-json.js

page : html css js js
html :
	@node gen/groq-html.js	
css :
	@node gen/groq-html.js
js :
	@node gen/groq-js.js
json :
	@node gen/groq-json.js